#!/bin/bash

set -x

export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR
./gradlew clean assemble --info
nohup ./gradlew run >> $OPENSHIFT_LOG_DIR/app.log $2>&1 &
